# Online Dataset
url_dataset: 'https://www.dropbox.com/s/ahffitzslifdzjn/fit-or-fat-dataset.zip?dl=1'
compressed_data_name: 'fit-or-fat-dataset.zip'

# Directories for dataset and checkpoints
data_dir: 'dataset'
data_dir_images: 'data'
features_dir: 'features'
features_file_name: 'features.txt'